### PR TITLE
Ion in input

### PR DESCRIPTION
**Pull request by bosonie**
Introduce the use of `IonData` in input. The implementation naturally leads to start to use validators. They will be heavily used in the coming refactoring. 
The use of `IonData` for the `SiestaBaseWorkChain` has not been allowed yet. It is an unnecessary effort to implement it when it will come natural in the coming refactoring (we will expose the inputs of `SiestaCalculation`.

### CODE REVIEW

**Comment by albgar** [comment]
I have put my comments and suggestions for some changes in the manual in the branch 'ion-ag'.

**Comment by bosonie** [comment]
Dear @albgar, I implemented your suggestions including the management of `lj` projectors.
Please note that in the old .ion.xml format, there was no way to distinguish which `j` was associated to the corresponding data. I assumed that the first listed `j` is always the smaller `j`. Meaning that the projector `(l=1 j=0.5)` comes before the  `(l=1 j=1.5)`, the projector `(l=2 j=1.5)` comes before the  `(l=2 j=2.5)` and so on. I hope it is correct.

**Comment by bosonie** [comment]
If you could approve I then merge.

**Comment by albgar** [comment]
> Please note that in the old .ion.xml format, there was no way to distinguish which `j` was associated to the corresponding data. I assumed that the first listed `j` is always the smaller `j`. Meaning that the projector `(l=1 j=0.5)` comes before the `(l=1 j=1.5)`, the projector `(l=2 j=1.5)` comes before the `(l=2 j=2.5)` and so on. I hope it is correct.

I have first checked the case in which Siesta reads a psf file and generates the projectors itself. In this case, "j-", that is, j=l-1/2, comes first.   
I now need to check what happens when Siesta reads the projectors directly from a PSML file.

**Comment by albgar** [comment]
How do I approve????

**Comment by bosonie** [comment]
Thanks a million! If you go in "Files changed", in the top right you have the "submit review" button!

**Review by albgar — APPROVED** [review]
Approve

**Pull request merged**
