### PR TITLE
Release1.2.0

### PR DESCRIPTION
**Pull request by bosonie**

### CODE REVIEW

**Comment by albgar** [comment]
When running the example_protocols.py script in examples/workflows, I get:
```
(pseudo) Alcina [develop]> verdi process report 7969
2021-05-18 08:21:59 [11997 | REPORT]: [7969|SiestaBaseWorkChain|prepare_inputs]: Preparing inputs of the SiestaBaseWorkChain
2021-05-18 08:21:59 [11998 | REPORT]: [7969|SiestaBaseWorkChain|run_process]: launching SiestaCalculation<7970> iteration #1
2021-05-18 08:23:35 [11999 | REPORT]: [7969|SiestaBaseWorkChain|results]: work chain completed after 1 iterations
2021-05-18 08:23:35 [12000 | REPORT]: [7969|SiestaBaseWorkChain|on_except]: Traceback (most recent call last):
  File "/Users/ag/code/miniconda3/envs/pseudo/lib/python3.9/site-packages/plumpy/process_states.py", line 230, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/Users/ag/code/miniconda3/envs/pseudo/lib/python3.9/site-packages/aiida/engine/processes/workchains/workchain.py", line 214, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/Users/ag/code/miniconda3/envs/pseudo/lib/python3.9/site-packages/plumpy/workchains.py", line 299, in step
    finished, result = self._child_stepper.step()
  File "/Users/ag/code/miniconda3/envs/pseudo/lib/python3.9/site-packages/plumpy/workchains.py", line 250, in step
    return True, self._fn(self._workchain)
  File "/Users/ag/code/aiida/PLUGIN/aiida_siesta_plugin/aiida_siesta/workflows/base.py", line 203, in postprocess
    output = node.get_outgoing(link_label_filter=name).one().node
  File "/Users/ag/code/miniconda3/envs/pseudo/lib/python3.9/site-packages/aiida/orm/utils/links.py", line 243, in one
    raise ValueError('no entries found')
ValueError: no entries found

2021-05-18 08:23:36 [12001 | REPORT]: [7969|SiestaBaseWorkChain|on_terminated]: remote folders will not be cleaned
````

The process info is:
```
(pseudo) Alcina [develop]> verdi process show 7969
Property     Value
-----------  ---------------------------------------
type         SiestaBaseWorkChain
state        Excepted <ValueError: no entries found>
pk           7969
uuid         4c66a636-9edc-4ef2-a079-f5de83bcbb59
label
description
ctime        2021-05-18 08:21:58.412373+00:00
mtime        2021-05-18 08:23:35.999578+00:00
computer     [1] localhost

Inputs          PK    Type
--------------  ----  -------------
pseudos
    Si          7719  PsmlData
basis           7964  Dict
clean_workdir   7968  Bool
code            3569  Code
kpoints         7965  KpointsData
max_iterations  7967  Int
options         7966  Dict
parameters      7963  Dict
structure       7962  StructureData

Outputs              PK  Type
-----------------  ----  ----------
forces_and_stress  7974  ArrayData
output_parameters  7973  Dict
remote_folder      7971  RemoteData
retrieved          7972  FolderData

Called          PK  Type
------------  ----  -----------------
iteration_01  7970  SiestaCalculation

Log messages
---------------------------------------------
There are 5 log messages for this calculation
Run 'verdi process report 7969' to see them
```

**Comment by albgar** [comment]
Sorry, the previous message was run in 'develop'.

**Comment by bosonie** [comment]
This is interesting. Can you explore what happened for the calculation in node 7998?

**Comment by albgar** [comment]
It finished correctly:

```
(pseudo) Alcina [Release1.2.0]> verdi process show 7998
Property     Value
-----------  ------------------------------------
type         SiestaCalculation
state        Finished [0]
pk           7998
uuid         6fbcd7ef-2a8a-4d15-bd7b-526520cba738
label
description
ctime        2021-05-18 08:33:41.304380+00:00
mtime        2021-05-18 08:35:17.681881+00:00
computer     [1] localhost

Inputs      PK    Type
----------  ----  -------------
pseudos
    Si      7719  PsmlData
basis       7992  Dict
code        3569  Code
kpoints     7993  KpointsData
parameters  7991  Dict
structure   7990  StructureData

Outputs            PK    Type
-----------------  ----  ----------
ion_files
    Si             8003  IonData
forces_and_stress  8002  ArrayData
output_parameters  8001  Dict
remote_folder      7999  RemoteData
retrieved          8000  FolderData

Caller          PK  Type
------------  ----  -------------------
iteration_01  7997  SiestaBaseWorkChain
```
It might be a problem with the linking of results to the output of the workchain.

**Comment by bosonie** [comment]
Thanks @albgar for the review. I implemented the changes to fix the problem.

**Review by albgar — APPROVED** [review]
OK. Now it works.

**Pull request merged**
