### PR TITLE
Floating dev

### PR DESCRIPTION
**Pull request by bosonie**
Introducing support for ghost states. They are specified through the `floating_sites` key to the `basis` input dictionary.

### CODE REVIEW

**Comment by bosonie** [comment]
@albgar I just realized I did not modify the `SiestaBaseWorkChain` to account for the lack of pseudopotentials for `floating_sites` in case the `pseudo_family` is passed and not an explicit list of pseudos. Will do it now and make a commit.

Also note that the checks on the `floating_sites` dictionaries are, for now, placed in the code in a bit strange place. This was the easiest way, and anyway I want to move all the validation checks in external validators in the upcoming refactoring of the the code.

**Comment by bosonie** [comment]
@albgar now it is ready for review. The addition of pseudos associate to `floating_sites` is done directly in `SiestaBaseWorkChain` for the moment. Again I want to refactor a lot there as well soon.

**Comment by albgar** [comment]
I approve, with some minor edits to the docs/plugins/siesta.rst file (see branch floating-dev-ag)

**Comment by bosonie** [comment]
Thanks @albgar. I included all your suggestions. I merge into develop.

**Pull request merged**
