### PR TITLE
New neb

### PR DESCRIPTION
**Pull request by bosonie**
Introduces the neb-base workchain.

### CODE REVIEW

**Comment by bosonie** [comment]
@albgar I introduced few modifications compared to your implementation:
1) Use of validators for the checks on the inputs
2) Modified the example to allow the specification of a LUA PATH to indicated where the flos library is.
3) Remove the scientific workflows, since they will be in the an external package

I will now write documentation and tests, bu you can start to try the code

**Comment by bosonie** [comment]
@albgar now it is fully ready to be merged. Let me know!

**Comment by albgar** [comment]
I am ready to approve.

**Comment by albgar** [comment]
I cannot figure out how to approve, or how to merge.

**Comment by bosonie** [comment]
I can do that, do not worry! In theory I need first to fix the pre-commit, then ask for new approval request. But no problem, I'll do it!

**Pull request merged**
